### ISSUE TITLE
Mark deprecated items as `#[deprecated]` properly

### ISSUE THREAD

**Issue by mrZalli** [dpc/hex2d-rs#11]
The[ `Coordinate`](https://docs.rs/hex2d/0.2.0/hex2d/struct.Coordinate.html) -struct seems to have a lot of methods whose only description is "old name for _x_".

I think these should be properly marked with the `deprecated` -attribute to make the compiler warn if anybody still uses them and a message with what they should use ( <https://doc.rust-lang.org/reference/attributes.html> ), or just removed in the next version bump.

But good job with this crate 👍

**Comment by dpc** [comment]
Agreed. I have sent you an invite. Feel free to take care of it. I am personally swamped with work and ideas, so I have to share the ownership with more people. :)

**Comment by mrZalli** [comment]
Well I'll fix it quickly. I could've also just fork the repo and create a pull request that you would check and merge.

Pull requests are a safer way of taking contributions, than giving many people access to the repository.

**Comment by dpc** [comment]
Then I have to review and merge the PR. 

Sharing is caring. I have a trust in you @mrZalli  :)

**Comment by dpc** [comment]
@mrZalli I've added you to crates.io owner as well. Feel free to add other people according to your own judgments.

Generally feel free to act as a owner of this crate, and if for whatever reason it's too much work, appoint more people. :D

**Comment by mrZalli** [comment]
That's an unexpected decision, but I'm gonna trust you. I'm not sure if I am able to use a lot of time with this on a long run, unless I start a project where this crate is used.
