### ISSUE TITLE
Serde, travis, nightly

### ISSUE THREAD

**Issue by rardiol** [dpc/hex2d-rs#13]
Adding serde serialization would be nice. Commit https://github.com/rardiol/hex2d-rs/commit/9d3a85a773777cb0828e7cea1dcd46bcd8929a21 from @bendst does it, not sure if keeping rustc-serialize is needed?

There's also a few commits from @bendst and me that might be nice to add maybe? https://github.com/rardiol/hex2d-rs/commits/master. Update the .travis for building and deploying (although now it needs to point to docs.rs) and use From trait.

 I also tried a experimental branch with nightly only features (impl Iterator): https://github.com/rardiol/hex2d-rs/commits/nightly, seems to be slightly faster according to my benchmark. Is there interest in adding it behind a feature flag?

I would do a pull request, but I dunno how to make a pull request of just some commits, is there a way?

**Comment by mrZalli** [comment]
From what I've heard Serde is the way to go with serialization since now it's available even in stable.

You do pull requests from your fork in the tab 'Pull requests' next to the 'Issues' tab in github

**Comment by rardiol** [comment]
Yes, I know how to do a pull request, it's just that I don't know a simple way (rebase and push multiple branches maybe?) of doing a pull request of just SOME commits in a branch, like in a cherry pick. Also, pull request someone's else code doesn't seem all that right.

**Comment by mrZalli** [comment]
Sorry! I was tired and didn't read your first properly. For that my git-fu isn't powerful enough to give a good answer though, but google should know.

**Comment by dpc** [comment]
```
git checkout someonesbranch
git checkout -b mynewbranch
git rebase -i origin/master
# pick the commits you like, delete all others
```
