### ISSUE TITLE
Passing the ownership.

### ISSUE THREAD

**Issue by dpc** [dpc/hex2d-rs#14]
Hi,

I am very happy that more people are using this crate and sad that I can not dedicate more work to maintain and improve it. Because of that, I'd like to set it free and make more community driven and easy to participate. I believe that people generally have good intentions.

I have sent a couple of invites to collaborators here and on crates.io. Please share this code liberally and improve for the benefit of everyone. Feel free to make any necessary changes, and agree with the active users what is the right way to go, when and what to release etc.

Thank you!

**Comment by serprex** [comment]
What of [hex2d-dpcext-rs](https://github.com/dpc/hex2d-dpcext-rs)? Perhaps bring it into this repo as a module?

**Comment by rardiol** [comment]
If dpcext is to be kept separate. this repo could contain hex2d and hex2d-dpcext as subcrates.

**Comment by dpc** [comment]
I thought noone is using `dpcext` . I've put there some hacky things that I was using in `rhex`. I think, if there's anything worthwhile, it should get ported, reviewed.

I personally don't care about code ownership (as long as it stays open), and I'm happy to assign/share ownership and relicense.

**Comment by serprex** [comment]
@dpc How do we publish new releases? With #27 being merged it'd be nice to bump to 0.3.1, but 0.3.0 never even hit crates.io

**Comment by dpc** [comment]
@serprex @rardiol I've sent you crates.io ownership invitations. Thanks!
