### ISSUE TITLE
Support f64 natively.

### ISSUE THREAD

**Issue by cheako** [dpc/hex2d-rs#24]
web_sys crate only works with f32 data for WebGL.

See: https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.CanvasRenderingContext2d.html

It would seem inefficient to convert back and forth.

**Comment by dpc** [comment]
Should be possible to parametrize everything over the float type, with a default to what we're doing right now. Go for it!

**Comment by cheako** [comment]
Already exists in master.
