### ISSUE TITLE
Compile aborting due unstable feature

### ISSUE THREAD

**Issue by oroid** [dpc/hex2d-rs#5]
Preconditions:
case1: Windows 7, 32bit, SP2
case2: OSX 10.9.5
rustc 1.0.0 (a59de37e9 2015-05-13) (built 2015-05-14)

compilation stop, log:
   Compiling hex2d v0.0.11 (...../rhex-hex2d)
src/lib.rs:63:1: 63:18 error: unstable feature
src/lib.rs:63 #![feature(core)]
              ^~~~~~~~~~~~~~~~~
note: this feature may not be used in the stable release channel
src/lib.rs:64:1: 64:22 error: unstable feature
src/lib.rs:64 #![feature(zero_one)]
              ^~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the stable release channel
src/lib.rs:65:1: 65:24 error: unstable feature
src/lib.rs:65 #![feature(step_trait)]
              ^~~~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the stable release channel
error: aborting due to 3 previous errors
Could not compile `hex2d`.

I've tested this lib by reason of compilation issue for game rhex.
It's do not build for Win7 and OSX

**Comment by dpc** [comment]
I'm sorry, but currently the code works only with `nightly` rust versions.

**Comment by dpc** [comment]
This has been fixed by #6
